### ISSUE TITLE
Promote 1.1.0-rc1 to 1.1.0, 2.0.0-rc1 to 2.0.0

### ISSUE THREAD

**Issue by taspeotis** [taspeotis/DeltaCompressionDotNet#12]
Placeholder to remind me to mark the NuGet packages as production instead of pre-release if nothing bad happens.

**Comment by taspeotis** [comment]
https://www.nuget.org/packages/DeltaCompressionDotNet/1.1.0-rc1
https://www.nuget.org/packages/DeltaCompressionDotNet/2.0.0-rc1

**Comment by jordyvaneijk** [comment]
Is this project over? Is the V2.0.0 also .net 2.0 / .net 4.0 compatible? Or is that only the version 1.1.0?

**Comment by taspeotis** [comment]
Hi, I still look after the project. v2 is .NET 2 compatible.

I'll bump these releases from RC1 status to RTM this weekend.

**Comment by jordyvaneijk** [comment]
Thank you so much for the quick response.

**Comment by taspeotis** [comment]
Hi, I've promoted `1.1.0-rc1` to `1.1.0`.

I'll promote `2.0.0-rc1` once https://github.com/Squirrel/Squirrel.Windows/pull/677 is resolved.

**Comment by taspeotis** [comment]
Squirrel has updated NuGet.

https://www.nuget.org/packages/squirrel.windows/1.4.1
https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.4.1

I will promote `2.0.0-rc1` soon.

**Comment by Thieum** [comment]
any block left for rtm?

**Comment by taspeotis** [comment]
Hi @Thieum: no blockers, I just got busy. I'll see what I can do in the next week or so.

**Comment by taspeotis** [comment]
Should be available shortly via https://www.nuget.org/packages/DeltaCompressionDotNet/2.0.0
